import React from "react";
import styles from "./Main.module.scss";
import classNames from "classnames/bind";
import { Link } from "react-router-dom";

// Reducer
import { useTagGet } from "hooks/lib";
import { ITagList } from "store/redux/tag";

const cx = classNames.bind(styles);

const test = [
  {
    title: "TEST",
    content: "Test...",
    date: "20180909",
    id: 4444,
    tag: "javascript"
  }
];

for (let i = 0; i < 30; i++) {
  test.push({
    title:
      "TESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTEST",
    content:
      "TESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTEST...",
    date: "20180909",
    id: i,
    tag: "typescript"
  });
}

function Main() {
  const tagList = useTagGet("tagList") as ITagList;

  return (
    <div className={cx("main-wrapper")}>
      {test.map(t => (
        <Link to={`/post/${t.id}`} className={cx("list")} key={t.id}>
          <div className={cx("header")}>
            <div className={cx("tag")}>
              <div className={cx("tag-title", t.tag)}>
                {tagList[t.tag].text}
              </div>
            </div>
            <div className={cx("date")}>{t.date}</div>
          </div>
          <div className={cx("title")}>
            <span className={cx("text")}>{t.title}</span>
          </div>
          <div className={cx("content")}>
            <span className={cx("text")}>{t.content}</span>
          </div>
        </Link>
      ))}
    </div>
  );
}

export default Main;
